// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptHostKey(arg1, arg2) {
  return window['go']['main']['DesktopApp']['AcceptHostKey'](arg1, arg2);
}

export function AcceptTunnelCertificate(arg1, arg2) {
  return window['go']['main']['DesktopApp']['AcceptTunnelCertificate'](arg1, arg2);
}

export function CancelDownload(arg1) {
  return window['go']['main']['DesktopApp']['CancelDownload'](arg1);
}

export function CancelUpload(arg1) {
  return window['go']['main']['DesktopApp']['CancelUpload'](arg1);
}

export function ClearSavedCredential(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ClearSavedCredential'](arg1, arg2);
}

export function CloseBrowserAccess(arg1) {
  return window['go']['main']['DesktopApp']['CloseBrowserAccess'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['DesktopApp']['CloseTerminal'](arg1);
}

export function ConnectAndOpenTerminal(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['ConnectAndOpenTerminal'](arg1, arg2, arg3);
}

export function ConnectionStatus(arg1) {
  return window['go']['main']['DesktopApp']['ConnectionStatus'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['DesktopApp']['CopyText'](arg1);
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['main']['DesktopApp']['DeleteProfile'](arg1, arg2);
}

export function DescribeUploadSelections(arg1) {
  return window['go']['main']['DesktopApp']['DescribeUploadSelections'](arg1);
}

export function DisconnectProfile(arg1, arg2) {
  return window['go']['main']['DesktopApp']['DisconnectProfile'](arg1, arg2);
}

export function DownloadStatus(arg1) {
  return window['go']['main']['DesktopApp']['DownloadStatus'](arg1);
}

export function ExportMCPAIGuide() {
  return window['go']['main']['DesktopApp']['ExportMCPAIGuide']();
}

export function ListProfiles() {
  return window['go']['main']['DesktopApp']['ListProfiles']();
}

export function ListRemoteDirectory(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ListRemoteDirectory'](arg1, arg2);
}

export function MCPAccessToken() {
  return window['go']['main']['DesktopApp']['MCPAccessToken']();
}

export function MCPClientConfig() {
  return window['go']['main']['DesktopApp']['MCPClientConfig']();
}

export function MCPStatus() {
  return window['go']['main']['DesktopApp']['MCPStatus']();
}

export function OpenBrowserResource(arg1, arg2) {
  return window['go']['main']['DesktopApp']['OpenBrowserResource'](arg1, arg2);
}

export function RegenerateMCPToken() {
  return window['go']['main']['DesktopApp']['RegenerateMCPToken']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveProfile(arg1) {
  return window['go']['main']['DesktopApp']['SaveProfile'](arg1);
}

export function SelectDownloadDirectory() {
  return window['go']['main']['DesktopApp']['SelectDownloadDirectory']();
}

export function SelectUploadDirectory() {
  return window['go']['main']['DesktopApp']['SelectUploadDirectory']();
}

export function SelectUploadFiles() {
  return window['go']['main']['DesktopApp']['SelectUploadFiles']();
}

export function StartDownload(arg1) {
  return window['go']['main']['DesktopApp']['StartDownload'](arg1);
}

export function StartMCP(arg1) {
  return window['go']['main']['DesktopApp']['StartMCP'](arg1);
}

export function StartUpload(arg1) {
  return window['go']['main']['DesktopApp']['StartUpload'](arg1);
}

export function StopMCP() {
  return window['go']['main']['DesktopApp']['StopMCP']();
}

export function TerminalWorkingDirectory(arg1) {
  return window['go']['main']['DesktopApp']['TerminalWorkingDirectory'](arg1);
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['DesktopApp']['TestSSHConnection'](arg1);
}

export function TestTunnelConnection(arg1) {
  return window['go']['main']['DesktopApp']['TestTunnelConnection'](arg1);
}

export function UploadStatus(arg1) {
  return window['go']['main']['DesktopApp']['UploadStatus'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['DesktopApp']['WriteTerminal'](arg1, arg2);
}
