// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {mcpserver} from '../models';
import {app} from '../models';

export function AcceptHostKey(arg1:string,arg2:string):Promise<void>;

export function AcceptTunnelCertificate(arg1:string,arg2:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CancelUpload(arg1:string):Promise<void>;

export function ClearSavedCredential(arg1:string,arg2:string):Promise<void>;

export function CloseBrowserAccess(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function ConnectAndOpenTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function ConnectionStatus(arg1:string):Promise<model.ConnectionStatus>;

export function CopyText(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string,arg2:boolean):Promise<void>;

export function DescribeUploadSelections(arg1:Array<string>):Promise<Array<model.UploadSelection>>;

export function DisconnectProfile(arg1:string,arg2:boolean):Promise<void>;

export function DownloadStatus(arg1:string):Promise<model.DownloadProgress>;

export function ExportMCPAIGuide():Promise<string>;

export function ListProfiles():Promise<Array<model.ConnectionProfile>>;

export function ListRemoteDirectory(arg1:string,arg2:string):Promise<model.RemoteDirectory>;

export function MCPAccessToken():Promise<string>;

export function MCPClientConfig():Promise<string>;

export function MCPStatus():Promise<mcpserver.Status>;

export function OpenBrowserResource(arg1:string,arg2:string):Promise<string>;

export function RegenerateMCPToken():Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveProfile(arg1:app.SaveProfileRequest):Promise<model.ConnectionProfile>;

export function SelectDownloadDirectory():Promise<string>;

export function SelectSSHPrivateKey():Promise<string>;

export function SelectUploadDirectory():Promise<model.UploadSelection>;

export function SelectUploadFiles():Promise<Array<model.UploadSelection>>;

export function StartDownload(arg1:model.DownloadRequest):Promise<model.DownloadProgress>;

export function StartMCP(arg1:number):Promise<mcpserver.Status>;

export function StartUpload(arg1:model.UploadRequest):Promise<model.UploadProgress>;

export function StopMCP():Promise<void>;

export function TerminalWorkingDirectory(arg1:string):Promise<string>;

export function TestSSHConnection(arg1:app.TestConnectionRequest):Promise<app.ConnectionTestResult>;

export function TestTunnelConnection(arg1:app.TestConnectionRequest):Promise<app.ConnectionTestResult>;

export function UploadStatus(arg1:string):Promise<model.UploadProgress>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
